name: Container Scan and Harden

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Hardened Docker Image
      run: |
        docker build -t webgoat-patched:secure -f hardened/Dockerfile.patched .

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: webgoat-patched:secure
        format: 'json'
        output: 'reports/trivy-report.json'
        severity: 'CRITICAL,HIGH'
        exit-code: 1

    - name: Run Dockle Scan
      uses: goodwithtech/dockle-action@main
      with:
        image: webgoat-patched:secure
        format: json
        output: reports/dockle-report.json
        exit-code: 1

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: reports/trivy-report.json

    - name: Upload Dockle Report
      uses: actions/upload-artifact@v4
      with:
        name: dockle-report
        path: reports/dockle-report.json
