name: Secure Docker Build & Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Download hardened JAR
      run: |
        mkdir -p hardened
        curl -L "https://github.com/MoeJaafar/webgoat-secure-build/releases/download/webgoat-hardened.jar/webgoat-hardened.jar" -o hardened/webgoat-hardened.jar
    
    - name: Create entrypoint.sh
      run: |
        mkdir -p hardened
        echo '#!/bin/sh' > hardened/entrypoint.sh
        echo 'exec java -Dserver.address=0.0.0.0 -Dhibernate.hbm2ddl.auto=none -jar /webgoat/webgoat.jar' >> hardened/entrypoint.sh
        chmod +x hardened/entrypoint.sh
        

    - name: Build Hardened Docker Image
      working-directory: hardened
      run: |
        export DOCKER_CONTENT_TRUST=1
        docker build -t webgoat-patched:secure -f Dockerfile.patched .
      
      
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -qO trivy.deb https://github.com/aquasecurity/trivy/releases/download/v0.60.0/trivy_0.60.0_Linux-64bit.deb
        sudo dpkg -i trivy.deb
      
    - name: Run Trivy scan (skipping large JAR)
      run: |
        mkdir -p reports
        trivy image webgoat-patched:secure \
          --skip-files webgoat/webgoat.jar \
          --format json \
          --severity CRITICAL,HIGH \
          --ignore-unfixed \
          -o reports/trivy-report.json
      

    - name: Install Dockle (Debian)
      run: |
          VERSION=$(
            curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
            grep '"tag_name":' | \
            sed -E 's/.*"v([^"]+)".*/\1/'
          )
          curl -L -o dockle.deb "https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.deb"
          sudo dpkg -i dockle.deb
          rm dockle.deb
        
      
      

    - name: Run Dockle scan with accepted keys
      run: |
          mkdir -p reports
          dockle \
            --exit-code 1 \
            --exit-level warn \
            --accept-key CIS-DI-0010:ARCH \
            --accept-key CIS-DI-0010:JAVA_HOME \
            --accept-key CIS-DI-0010:PATH \
            --accept-key CIS-DI-0010:JAVA_VERSION \
            --accept-key CIS-DI-0010:LANG \
            --accept-key CIS-DI-0010:fileEncoding \
            --accept-key CIS-DI-0010:--chmod \
            --format json \
            --output reports/dockle-report.json \
            webgoat-patched:secure
      

    - name: Upload scan reports
      uses: actions/upload-artifact@v4
      with:
        name: docker-security-reports
        path: reports/
