name: Secure Docker Build & Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Download hardened JAR
      run: |
        mkdir -p hardened
        curl -L "https://github.com/MoeJaafar/webgoat-secure-build/releases/download/webgoat-hardened.jar/webgoat-hardened.jar" -o hardened/webgoat-hardened.jar
    
    - name: Create entrypoint.sh
      run: |
        mkdir -p hardened
        echo '#!/bin/sh' > hardened/entrypoint.sh
        echo 'exec java -Dserver.address=0.0.0.0 -Dhibernate.hbm2ddl.auto=none -jar /webgoat/webgoat.jar' >> hardened/entrypoint.sh
        chmod +x hardened/entrypoint.sh
        

    - name: Build Hardened Docker Image
      working-directory: hardened
      run: |
        export DOCKER_CONTENT_TRUST=1
        docker build -t webgoat-patched:secure -f Dockerfile.patched .
      
      
        - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO trivy.deb https://github.com/aquasecurity/trivy/releases/download/v0.60.0/trivy_0.60.0_Linux-64bit.deb
          sudo dpkg -i trivy.deb
      
    - name: Run Trivy scan (skipping large JAR)
      run: |
        mkdir -p reports
        trivy image webgoat-patched:secure \
          --skip-files webgoat/webgoat.jar \
          --format json \
          --severity CRITICAL,HIGH \
          --ignore-unfixed \
          -o reports/trivy-report.json
      
      
      

    - name: Run Dockle scan
      uses: goodwithtech/dockle-action@main
      with:
        image: webgoat-patched:secure
        format: json
        output: reports/dockle-report.json

    - name: Upload scan reports
      uses: actions/upload-artifact@v4
      with:
        name: docker-security-reports
        path: reports/
